
language: "java"  # or "python"

paths:
  python_prompts:
    tgt_exception_prompt: "../prompts/python/tgt_exception_prompt.txt"
    tgt_coverage_prompt: "../prompts/python/tgt_coverage_prompt.txt"
    cvg_prompt: "../prompts/python/cvg_prompt.txt"
    tgt_exception_instructions: "../prompts/python/tgt_exception_prompt_instructions.txt"
    tgt_coverage_instructions: "../prompts/python/tgt_coverage_prompt_instructions.txt"
    cvg_instructions: "../prompts/python/cvg_prompt_instructions.txt"
    codepilot_cvg_prompt: "../prompts/python/codepilot_main-oneshot-plan-prompt.txt"
    codepilot_cvg_instructions: "../prompts/python/codepilot_oneshot-plan-prompt.txt"

  java_prompts:
    tgt_exception_prompt: "../prompts/java/tgt_exception_prompt.txt"
    tgt_coverage_prompt: "../prompts/java/tgt_coverage_prompt.txt"
    cvg_prompt: "../prompts/java/cvg_prompt.txt"
    tgt_exception_instructions: "../prompts/java/tgt_exception_prompt_instructions.txt"
    tgt_coverage_instructions: "../prompts/java/tgt_coverage_prompt_instructions.txt"
    cvg_instructions: "../prompts/java/cvg_prompt_instructions.txt"
    codepilot_cvg_prompt: "../prompts/java/codepilot_main-oneshot-plan-prompt.txt"
    codepilot_cvg_instructions: "../prompts/java/codepilot_oneshot-plan-prompt.txt"

  dataset: "../dataset/java_dataset.json"
  output_folder: "../results"
  java_program: "Main.java"
  python_program: "program.py"


azure_openai:
  tgt:
    api_key: "YOUR_OPENAI_API_KEY"
    api_version: "YOUR_OPENAI_API_VERSION"
    model: YOUR_OPENAI_API_MODEL_VERSION
    azure_endpoint: "YOUR_OPENAI_API_ENDPOINT"

  ccp:
    api_key: "YOUR_OPENAI_API_KEY"
    api_version: "YOUR_OPENAI_API_VERSION"
    model: YOUR_OPENAI_API_MODEL_VERSION
    azure_endpoint: "YOUR_OPENAI_API_ENDPOINT"

